#!/bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width		2
bspc config window_gap			5
bspc config split_ratio			0.5
bspc config focus_follows_pointer	true
bspc config focused_border_color	"#FFFFFF"
bspc config normal_border_color		"#858585"

sxhkd &
setxkbmap it &
pipewire &
wireplumber &
pipewire-pulse &
picom --backend xrender &
polybar &
xwallpaper --stretch ~/.config/bspwm/cynn.png &
xset -dpms &
xset s off &
