#!/bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width		1
bspc config window_gap			2
bspc config split_ratio			1
bspc config focus_follows_pointer	true
bspc config focused_border_color	"#FFFFFF"
bspc config normal_border_color		"#858585"

pkill pipewire
pkill wireplumber
pkill pipewire-pulse
sleep 1
pipewire &
wireplumber &
pipewire-pulse &
sxhkd &
picom --backend xrender &
polybar &
xwallpaper --stretch ~/.config/bspwm/sdn.png &
xset -dpms &
xset s off &
setxkbmap it &
